# Generated by Django 3.2.6 on 2021-08-20 00:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='events',
            old_name='details',
            new_name='brand',
        ),
        migrations.RenameField(
            model_name='events',
            old_name='title',
            new_name='country',
        ),
        migrations.AddField(
            model_name='events',
            name='staff',
            field=models.CharField(default=0, max_length=100),
            preserve_default=False,
        ),
    ]
